export const images = {
  hero: "/images/teachers-hero-Ca-eJz8B.jpg",
  webinar: "/images/news-webinar-BCE9OWIC.jpg",
  resource: "/images/news-resource-Dtx0iGs0.jpg",
  project: "/images/news-project-C-iZN8kv.jpg",
};

export const nav = [
  { label: "Главна табла", to: "/" },
  { label: "Мој профил", to: "/profil" },
  { label: "Огласна табла", to: "/oglasi" },
  { label: "Обуки", to: "/obuki" },
  { label: "Ресурси", to: "/resursi" },
  { label: "Настани", to: "/nastani" },
  { label: "Даскалски форум", to: "/forum" },
  { label: "Календар", to: "/kalendar" },
];

export const resources = [
  {
    id: "aktivno-ucenje",
    title: "Прирачник за активно учење",
    category: "Прирачници",
    source: "LEAD",
    kind: "Прирачник",
    type: "PDF",
    author: "LEAD тим",
    date: "10 Јуни 2025",
    detail: "48 страници со практични техники за активно вклучување на учениците.",
  },
  {
    id: "digitalna-ucilnica",
    title: "Дигитални алатки во училницата",
    category: "Презентации",
    source: "Наставници",
    kind: "Презентација",
    type: "PPTX",
    author: "Марија Трајкова",
    date: "8 Јуни 2025",
    detail: "Преглед на достапни алатки и примери за нивна примена во наставата.",
  },
  {
    id: "kriticko-mislenje",
    title: "Работни листови за критичко мислење",
    category: "Работни листови",
    source: "Наставници",
    kind: "Работен лист",
    type: "DOCX",
    author: "Ана Петровска",
    date: "4 Јуни 2025",
    detail: "Подготвени активности за анализа, дискусија и аргументација.",
  },
  {
    id: "inklusivna-nastava",
    title: "Методи за инклузивна настава",
    category: "Методички материјали",
    source: "LEAD",
    kind: "Прирачник",
    type: "PDF",
    author: "LEAD тим",
    date: "30 Мај 2025",
    detail: "Методички насоки за создавање пристапна и поддржувачка училница.",
  },
  {
    id: "otvoreni-alatki",
    title: "Отворени образовни алатки",
    category: "Корисни линкови",
    source: "LEAD",
    kind: "Линк",
    type: "LINK",
    author: "Клуб на наставници",
    date: "28 Мај 2025",
    detail: "Курирана колекција на бесплатни дигитални алатки за наставници.",
  },
  {
    id: "proektna-nastava",
    title: "Проектна настава: од идеја до реализација",
    category: "Презентации",
    source: "Наставници",
    kind: "Видео",
    type: "VIDEO",
    author: "Горан Николов",
    date: "20 Мај 2025",
    detail: "Снимена практична сесија за планирање и оценување на ученички проекти.",
  },
  {
    id: "rubriki-generator",
    title: "Генератор на рубрики за оценување",
    category: "Алатки",
    source: "LEAD",
    kind: "Алатка",
    type: "WEB",
    author: "LEAD тим",
    date: "16 Мај 2025",
    detail: "Онлајн алатка за брзо креирање рубрики според целите на часот.",
  },
  {
    id: "izlezni-karticki",
    title: "Излезни картички за крај на час",
    category: "Работни листови",
    source: "Наставници",
    kind: "Работен лист",
    type: "PDF",
    author: "Елена Јованова",
    date: "12 Мај 2025",
    detail: "20 печатливи картички за брза повратна информација од учениците.",
  },
  {
    id: "roditeli-sredba",
    title: "Сценарио за родителска средба",
    category: "Друго",
    source: "Наставници",
    kind: "Друго",
    type: "DOCX",
    author: "Весна Маркова",
    date: "5 Мај 2025",
    detail: "Структура и прашања за продуктивна средба со родители.",
  },
];

export const topics = [
  {
    id: "motivacija",
    title: "Како да го мотивираме ученикот?",
    category: "Методика и пракса",
    author: "Илија Станковски",
    replies: 2,
    views: 0,
    time: "пред 2 часа",
    body: "Кои пристапи ви даваат најдобри резултати кога ученикот ја губи енергијата на средината од часот?",
    messages: [],
  },
  {
    id: "digitalni-alatki",
    title: "Дигитални алатки за наставата",
    category: "Технологија",
    author: "Марија Трајкова",
    replies: 1,
    views: 0,
    time: "пред 5 часа",
    body: "Кои бесплатни алатки ви се најстабилни за час од 40 минути?",
    messages: [],
  },
  {
    id: "dobra-praktika",
    title: "Кратки цели на почетокот на часот",
    category: "Добра практика",
    author: "Ана Петровска",
    replies: 0,
    views: 0,
    time: "вчера",
    body: "Ги запишувам трите цели на таблата пред да почне активноста.",
    messages: [],
  },
];

export const events = [
  {
    id: "vebinar",
    date: "2025-06-12",
    day: "12",
    month: "Јун",
    title: "Вебинар: Нови методи во наставата",
    kind: "Вебинар",
    location: "Онлајн",
    time: "10:00",
    status: "Претстои",
    detail: "Едночасовна онлајн сесија за методи што ја зголемуваат вклученоста на учениците.",
  },
  {
    id: "ikt",
    date: "2025-06-18",
    day: "18",
    month: "Јун",
    title: "Работилница за ИКТ во образованието",
    kind: "Работилница",
    location: "Скопје",
    time: "14:00",
    status: "Претстои",
    detail: "Практична работилница со алатки за планирање и следење на дигитална настава.",
  },
  {
    id: "inkluzija",
    date: "2025-06-22",
    day: "22",
    month: "Јун",
    title: "Креирање план за инклузија",
    kind: "Обука",
    location: "Онлајн",
    time: "18:00",
    status: "Претстои",
    detail: "Работиме на училишен план за инклузија со конкретни чекори за тимот.",
  },
  {
    id: "mentor",
    date: "2025-05-30",
    day: "30",
    month: "Мај",
    title: "Менторска средба за нови наставници",
    kind: "Средба",
    location: "Битола",
    time: "12:00",
    status: "Завршен",
    detail: "Завршена средба за поддршка на наставници во првите години од кариерата.",
  },
];

export const opportunities = [
  {
    day: "15",
    title: "Летна школа за инклузивно образование",
    category: "ОТВОРЕН ПОВИК",
    type: "Обука",
    deadline: "15 Јуни",
    description: "Практична петдневна програма за основно образование.",
    urgent: true,
  },
  {
    day: "22",
    title: "Грант за училишни проекти",
    category: "ФИНАНСИРАЊЕ",
    type: "Грант",
    deadline: "22 Јуни",
    description: "Поддршка за иновативни ученички иницијативи.",
    urgent: false,
  },
  {
    day: "30",
    title: "Програма за професионален развој",
    category: "ПРОГРАМА",
    type: "Обука",
    deadline: "30 Јуни",
    description: "Менторирана програма за наставници во три модули.",
    urgent: false,
  },
  {
    day: "04",
    title: "Повик за наставници-ментори",
    category: "НОВО",
    type: "Менторство",
    deadline: "4 Јули",
    description: "Споделете искуство со колеги на почетокот од кариерата.",
    urgent: false,
  },
];

export const noticeCategories = ["Повик", "Обука", "Конкурс", "Грант", "Настан", "Важно", "Рок"];

export const notices = [
  { title: "Летна школа за инклузивно образование", category: "Повик", day: "15", month: "ЈУН", status: "ПОСЛЕДЕН ДЕН", priority: true, text: "Петдневна практична програма за основно образование." },
  { title: "Грант за училишни проекти", category: "Грант", day: "22", month: "ЈУН", status: "РОКОТ ИСТЕКУВА", priority: true, text: "Поддршка до 60.000 денари за ученички иницијативи." },
  { title: "Програма за професионален развој", category: "Обука", day: "30", month: "ЈУН", status: "ОТВОРЕНА ПРИЈАВА", priority: false, text: "Менторирана програма во три модули." },
  { title: "Повик за наставници-ментори", category: "Повик", day: "04", month: "ЈУЛ", status: "НОВО", priority: false, text: "Поддржете колеги на почетокот од кариерата." },
  { title: "Промена на терминот за ИКТ работилница", category: "Важно", day: "18", month: "ЈУН", status: "ВАЖНО", priority: true, text: "Работилницата почнува во 14:00 наместо 13:00." },
  { title: "Конкурс: Наставник иноватор 2025", category: "Конкурс", day: "30", month: "ЈУН", status: "ОТВОРЕНО", priority: false, text: "Претставете добра практика пред заедницата." },
  { title: "Годишно собрание на Клубот", category: "Настан", day: "27", month: "ЈУН", status: "НАСКОРО", priority: false, text: "Скопје, 11:00 — потврдете присуство." },
  { title: "Обука за дигитална безбедност", category: "Обука", day: "25", month: "ЈУН", status: "ОТВОРЕНА ПРИЈАВА", priority: false, text: "Сертифицирана онлајн обука во два модули." },
  { title: "Рок за годишни извештаи на клубовите", category: "Рок", day: "20", month: "ЈУН", status: "РОКОТ ИСТЕКУВА", priority: true, text: "Регионалните координатори доставуваат извештај." },
  { title: "Мини-грантови за STEAM активности", category: "Грант", day: "10", month: "ЈУЛ", status: "НОВО", priority: false, text: "До 20.000 денари за опрема и материјали." },
  { title: "Конкурс за ученички есеј", category: "Конкурс", day: "12", month: "ЈУЛ", status: "ОТВОРЕНО", priority: false, text: "Тема: Училиштето на мојот сон." },
  { title: "Нова верзија на Водичот за членови", category: "Важно", day: "02", month: "ЈУН", status: "ВАЖНО", priority: false, text: "Достапна во Документи на клубот." },
];

export const calendarCategories = ["Обуки", "Настани", "Работилници", "Рокови", "Други активности"];

export const calendarItems = [
  { id: "c1", day: 3, title: "Средба на регионален клуб", category: "Настани", time: "17:00", location: "Штип", text: "Месечна средба на членовите од источниот регион." },
  { id: "c2", day: 6, title: "Модул 1: Инклузивна училница", category: "Обуки", time: "16:00", location: "Онлајн", text: "Прв модул од обуката со снимка и прашалник." },
  { id: "c3", day: 10, title: "Рок: Предлог-теми за форумот", category: "Рокови", time: "23:59", location: "Платформа", text: "Испратете предлози за тематски дискусии." },
  { id: "c4", day: 12, title: "Вебинар: Нови методи во наставата", category: "Настани", time: "10:00", location: "Онлајн", text: "Вебинар со практични примери од училници." },
  { id: "c5", day: 15, title: "Рок: Летна школа за инклузија", category: "Рокови", time: "23:59", location: "Платформа", text: "Последен ден за пријава на летната школа." },
  { id: "c6", day: 18, title: "Работилница за ИКТ", category: "Работилници", time: "14:00", location: "Скопје", text: "Практична работилница за дигитални алатки." },
  { id: "c7", day: 18, title: "Консултации со ментори", category: "Други активности", time: "18:00", location: "Онлајн", text: "Отворени консултации за нови наставници." },
  { id: "c8", day: 20, title: "Модул 2: Дигитални алатки", category: "Обуки", time: "16:00", location: "Онлајн", text: "Втор модул со снимка и завршен прашалник." },
  { id: "c9", day: 22, title: "Рок: Грант за училишни проекти", category: "Рокови", time: "23:59", location: "Платформа", text: "Краен рок за апликации за грантот." },
  { id: "c10", day: 25, title: "Работилница: Проектно учење", category: "Работилници", time: "13:00", location: "Битола", text: "Од идеја до реализација на ученички проект." },
  { id: "c11", day: 27, title: "Годишно собрание на Клубот", category: "Настани", time: "11:00", location: "Скопје", text: "Преглед на годината и планови за наредната." },
  { id: "c12", day: 30, title: "Рок: Програма за професионален развој", category: "Рокови", time: "23:59", location: "Платформа", text: "Последен ден за пријава." },
];

export const documents = [
  {
    title: "Годишна програма за работа",
    type: "DOCX",
    folder: "Програми",
    size: "184 KB",
    date: "12 Јуни 2025",
    featured: true,
  },
  {
    title: "Шаблон за подготовка на час",
    type: "DOCX",
    folder: "Наставни материјали",
    size: "92 KB",
    date: "10 Јуни 2025",
    featured: true,
  },
  {
    title: "Водич за формативно оценување",
    type: "PDF",
    folder: "Водичи",
    size: "1.2 MB",
    date: "6 Јуни 2025",
    featured: false,
  },
  {
    title: "Евиденција за проектни активности",
    type: "XLSX",
    folder: "Формулари",
    size: "240 KB",
    date: "2 Јуни 2025",
    featured: false,
  },
  {
    title: "Согласност за учество на настан",
    type: "PDF",
    folder: "Формулари",
    size: "140 KB",
    date: "29 Мај 2025",
    featured: false,
  },
  {
    title: "Програма за менторска поддршка",
    type: "PDF",
    folder: "Програми",
    size: "860 KB",
    date: "25 Мај 2025",
    featured: false,
  },
];

export const trainings = [
  {
    id: "inkluzivna-ucilnica",
    title: "Инклузивна училница во пракса",
    category: "Инклузија",
    description: "Алатки за планирање на пристапна настава и поддршка на секој ученик.",
    duration: "12 часа",
    format: "Во живо",
    level: "Средно ниво",
    status: "Отворена",
    image: "webinar",
  },
  {
    id: "digitalni-alatki",
    title: "Дигитални алатки за активна настава",
    category: "Технологија",
    description: "Практична примена на достапни дигитални алатки во секојдневниот час.",
    duration: "8 часа",
    format: "Онлајн",
    level: "Почетно ниво",
    status: "Отворена",
    image: "project",
  },
  {
    id: "proektno-ucenje",
    title: "Проектно учење од идеја до реализација",
    category: "Методика",
    description: "Креирајте автентични проекти што ги поврзуваат предметите и заедницата.",
    duration: "10 часа",
    format: "Хибридно",
    level: "Напредно",
    status: "Наскоро",
    image: "resource",
  },
  {
    id: "formativno-ocenuvanje",
    title: "Формативно оценување без стрес",
    category: "Оценување",
    description: "Јасна повратна информација, рубрики и ученичка самопроценка во пракса.",
    duration: "6 часа",
    format: "Онлајн",
    level: "Сите нивоа",
    status: "Завршена",
    image: "webinar",
  },
];

export const news = [
  {
    type: "Настан",
    signal: "НОВО",
    tone: "fresh",
    title: "Вебинар: Нови методи во наставата",
    date: "12 Јуни 2025",
    meta: "Онлајн",
    image: images.webinar,
    to: "/nastani",
  },
  {
    type: "Ресурс",
    signal: "НОВО",
    tone: "fresh",
    title: "Прирачник за активно учење",
    date: "10 Јуни 2025",
    meta: "48 страници",
    image: images.resource,
    to: "/resursi/aktivno-ucenje",
  },
  {
    type: "Обука",
    signal: "ОТВОРЕНИ ПРИЈАВИ",
    tone: "open",
    title: "Проектни активности во училиште",
    date: "9 Јуни 2025",
    meta: "Онлајн · 8 часа",
    image: images.project,
    to: "/obuki",
  },
];

export const juneDays = [
  26, 27, 28, 29, 30, 31, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 1, 2, 3, 4, 5, 6,
];

export const notifications = [
  { id: "res", title: "Нов ресурс во заедницата", time: "пред 1 час", to: "/resursi/aktivno-ucenje" },
  { id: "cal", title: "Потсетник: вебинар на 12 јуни", time: "пред 3 часа", to: "/kalendar" },
  { id: "forum", title: "Нов одговор на ваша тема", time: "пред 5 часа", to: "/forum/motivacija" },
];
